export const UPDATE_SEARCH_INPUT = "UPDATE_SEARCH_INPUT";
export const UPDATE_SEARCH_RESULT = "UPDATE_SEARCH_RESULT";
export const SHOW_SEARCH_PAGE = "SHOW_SEARCH_PAGE";
export const HIDE_SEARCH_PAGE = "HIDE_SEARCH_PAGE";
export const START_SEARCH = "START_SEARCH";
